server:
    port: 8082
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/board
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        properties:
            hibernate:
                showsql: false
                formatsql: false
                temp:
                    use_jdbc_metadata_defaults: false
        hibernate:
            ddl-auto: validate
        open-in-view: false
    servlet:
        multipart:
            enabled: true
            max-file-size: 15MB
            max-request-size: 15MB
    liquibase:
        change-log: classpath:db.changelog/changelog-master.xml
logging:
    level:
        org:
            hibernate:
                type: error

#docker run --name postgres-board-db -e POSTGRES_DB=board -e POSTGRES_PASSWORD=root -d -p 5432:5432 postgres

